name: Pull Request
run-name: Pull Request on ${{ github.ref_name }} by @${{ github.actor }}

on: 
  - pull_request
  - workflow_dispatch


jobs:

  validate:
    runs-on:
      # easier to use Windows runner with the windowsgui build flag
      - windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build -v -o runsyncapps -ldflags="-H windowsgui" ./cmd

  vulnerability-check:
    runs-on:
      - ubuntu-latest
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: './go.mod'
          go-package: ./...
          check-latest: true
